AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Weather Application (Phase 2)

Resources:

  WeatherEventLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.symphonia.WeatherEventLambda::handler
      Runtime: java8
      MemorySize: 256
      Timeout: 10
      CodeUri: target/lambda.jar
