AWSTemplateFormatVersion: '2010-09-09'
Description: OSCON 2017 Serverless Tutorial Build Pipeline

Parameters:
  ServerlessStackName:
    Type: String
    Default: oscon-2017-tutorial
    AllowedPattern: "[A-Za-z0-9-]+"
  ServerlessStackChangeSetName:
    Type: String
    Default: change-set
    AllowedPattern: "[A-Za-z0-9-]+"
  ServerlessStackTemplateFileName:
    Type: String
    Default: packaged-sam.yml

Resources:

  CodeBuildJavaProject:
      Type: AWS::CodeBuild::Project
      DependsOn: CodeBuildRole
      Properties:
        Artifacts:
          Type: CODEPIPELINE
        Environment:
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/java:openjdk-8
          Type: LINUX_CONTAINER
          EnvironmentVariables:
          - Name: CFN_PACKAGE_S3_BUCKET
            Value: !Ref CfnPackageS3Location
        Name: !Sub ${AWS::StackName}CodeBuildJavaProject
        ServiceRole: !Ref CodeBuildRole
        Source:
          Type: CODEPIPELINE

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStoreS3Location
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          InputArtifacts: []
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: '1'
            Provider: S3
          OutputArtifacts:
          - Name: MyApp
          Configuration:
            S3Bucket: !Ref SourceS3Location
            S3ObjectKey: source.zip
          RunOrder: 1
      - Name: Build
        Actions:
        - Name: Build
          ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
          OutputArtifacts:
            - Name: MyAppBuild
          InputArtifacts:
            - Name: MyApp
          Configuration:
              ProjectName: !Ref CodeBuildJavaProject
          RunOrder: 1
      - Name: Deploy
        Actions:
        - Name: CreateChangeSet
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          InputArtifacts:
            - Name: MyAppBuild
          Configuration:
            ActionMode: CHANGE_SET_REPLACE
            Capabilities: CAPABILITY_IAM
            RoleArn: !GetAtt CloudformationRole.Arn
            StackName: !Ref ServerlessStackName
            ChangeSetName: !Ref ServerlessStackChangeSetName
            TemplatePath: !Sub "MyAppBuild::${ServerlessStackTemplateFileName}"
          RunOrder: 1
        - Name: ExecuteChangeSet
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1'
          Configuration:
            ActionMode: CHANGE_SET_EXECUTE
            Capabilities: CAPABILITY_IAM
            ChangeSetName: !Ref ServerlessStackChangeSetName
            RoleArn: !GetAtt CloudformationRole.Arn
            StackName: !Ref ServerlessStackName
          RunOrder: 2

  SourceS3Location:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  ArtifactStoreS3Location:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  CfnPackageS3Location:
    Type: AWS::S3::Bucket

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess #TODO: Reduce permissions

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess #TODO: Reduce permissions

  CloudformationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess #TODO: Reduce permissions
