AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Weather Application (Phase 1)

Resources:

  EventsIngestLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.symphonia.EventsIngestLambda::handler
      Runtime: java8
      MemorySize: 256
      Timeout: 10
      CodeUri: events-ingest-lambda-phase1/target/lambda.jar
